todo/urls.py
from django.urls import path
from .views import MyView, TaskCreateView, TaskDetailView, TaskDeleteView, TaskSearchView

urlpatterns = [
    path('', MyView.as_view(), name='todo'),
    path('create/', TaskCreateView.as_view(), name='taskcreate'),
    path('todo_detail/<int:pk>', TaskDetailView.as_view(), name='taskdetail'),
    path('delete/<int:pk>', TaskDeleteView.as_view(), name='task_delete'),
    path('search/', TaskSearchView.as_view(), name='task_search')
]

todosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

todo/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.title} {self.details}'

todo/views.py
from django.shortcuts import render
from .models import Todo
from django.views.generic import ListView, DetailView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy


# Create your views here.
class MyView(ListView):
    model = Todo
    template_name = 'todo/index.html'


class TaskCreateView(CreateView):
    model = Todo
    template_name = 'todo/createtask.html'
    fields = '__all__'
    success_url = reverse_lazy('todo')


class TaskDetailView(DetailView):
    model = Todo


class TaskDeleteView(DeleteView):
    model = Todo
    template_name = 'todo/delete.html'
    success_url = reverse_lazy('todo')


class TaskSearchView(ListView):
    model = Todo
    template_name = 'todo/index.html'
    queryset = Todo.objects.all()

    def get_queryset(self):
        result = self.request.GET.get('search_term')
        return Todo.objects.filter(title__icontains=result)

todo/templates/todo/createtask.html
{% extends 'todo/index.html' %}
{% block content%}
{% load widget_tweaks %}
    <div class="container">
        <h3> New Task </h3>
    <form method="POST" action="" class="container mt-4">
        {% csrf_token %}
        <div class="form-group">
        {{ form.title.label_tag }}
        {{ form.title|add_class:"form-control" }}
    </div>
        <div class="form-group">
        {{ form.details.label_tag }}
        {{ form.details|add_class:"form-control" }}
    </div>
        <div class="form-group">
        {{ form.date.label_tag }}
        {{ form.date|add_class:"form-control" }}
    </div>
        <input type="submit" value="Save">
    </form>
    </div>

{% endblock %}

todo/templates/todo/delete.html
{% extends 'todo/index.html' %}
{% block content %}
    <div class="container">
        <form method="POST" action="">
            {% csrf_token %}
            <p>
                Are you sure you want to delete "{{todo.title}}" ?
            </p>
            <button class="btn btn-danger ml-2" type="submit">Delete</button>
        </form>
    </div>
{% endblock content %}

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style type="text/css" media="screen">
        ul{
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }
        li{
            float: left;
        }
        li a{
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        .active{
            background-color: #04AA6D;
        }
        li a:hover{
            background-color: #66ff66;
        }
        table,th,td{
            border: 1px solid;
            border-color: #96d4d4;
            padding: 15px;
        }
        a{
            text-decoration: none;
        }
        form{
            padding: 10px;
        }
    </style>
    <div class="container">
        <ul>
            <li><a href="{% url 'todo' %}">Home</a></li>
            <li style="float : right"><a href="{% url 'taskcreate' %}">+ Add New Task</a></li>
        </ul>
    </div>
</head>
<div class="container">
    <form action="{% url 'task_search' %}" method="get">
        <input type="text" name="search_term" placeholder="Search here">
        <button type="submit" >Search</button>
    </form>
</div>
<body>
    {% block content%}
    <div class="container">
    {% for todo in todo_list %}
        <table style="width: 100%">
            <tr>
                <td style="width: 80%"><a href="{% url 'taskdetail' todo.pk %}">{{todo.title}}</a></td>
                <td style="width: 20%"><a href="{% url 'task_delete' todo.pk %} ">Delete</a></td>
            </tr>
        </table>
    {% endfor%}
    <a href="{% url 'taskcreate' %}">Add New Task</a>
        </div>
    {% endblock content%}

</body>
</html>

todo/templates/todo/todo_detail.html
{% extends 'todo/index.html' %}
{% block content %}
<div class="container">
    <h1>{{todo.title}}</h1>
    <p>{{todo.details}}</p>
    <p>{{todo.date}}</p>
</div>
{% endblock content %}